[2022-06-13 21:50:03,594] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_first_dag.fetch_data_from_predicthq manual__2022-06-13T19:49:56.567509+00:00 [queued]>
[2022-06-13 21:50:03,604] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: my_first_dag.fetch_data_from_predicthq manual__2022-06-13T19:49:56.567509+00:00 [queued]>
[2022-06-13 21:50:03,605] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 21:50:03,605] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-06-13 21:50:03,606] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 21:50:03,619] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_data_from_predicthq> on 2022-06-13 19:49:56.567509+00:00
[2022-06-13 21:50:03,623] {standard_task_runner.py:52} INFO - Started process 2345 to run task
[2022-06-13 21:50:03,628] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'fetch_data_from_predicthq', 'manual__2022-06-13T19:49:56.567509+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpbd48jv93', '--error-file', '/tmp/tmp2mec3kvo']
[2022-06-13 21:50:03,629] {standard_task_runner.py:80} INFO - Job 24: Subtask fetch_data_from_predicthq
[2022-06-13 21:50:03,691] {logging_mixin.py:109} INFO - Running <TaskInstance: my_first_dag.fetch_data_from_predicthq manual__2022-06-13T19:49:56.567509+00:00 [running]> on host LAPTOP-M1F9EL62.localdomain
[2022-06-13 21:50:03,741] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=fetch_data_from_predicthq
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T19:49:56.567509+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-13T19:49:56.567509+00:00
[2022-06-13 21:50:03,743] {logging_mixin.py:109} INFO - Hello Airflow - This is Task with task_number: task3
[2022-06-13 21:50:03,743] {logging_mixin.py:109} INFO - kwargs['dag_run'] 2022-06-13 19:49:56.567509+00:00
[2022-06-13 21:50:03,744] {python.py:175} INFO - Done. Returned value was: None
[2022-06-13 21:50:03,750] {taskinstance.py:1278} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=fetch_data_from_predicthq, execution_date=20220613T194956, start_date=20220613T195003, end_date=20220613T195003
[2022-06-13 21:50:03,799] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-06-13 21:50:03,860] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
